workspace:
  base: /bzmoon
  path: repo/${DRONE_REPO_SLUG}

pipeline:
  bundler:
    image: docker.dock1.spaceway.network/bzone/bztools:latest
    when:
      event:
        - tag
    commands:
      - mkdir -p /tmp/bzmoon
      - mkdir -p /tmp/bzmoon2
      - moonc /bzmoon/repo/src
      - cp /bzmoon/repo/extra/* /tmp/bzmoon
      - find /bzmoon/repo/src -type f -name "*.lua" -exec cp {} /tmp/bzmoon \;
      - cp /bzmoon/repo/.squish /tmp/bzmoon
      - cp -r /tmp/bzmoon/. /tmp/bzmoon2/
      - python3 /bztools/luaSquish.py /tmp/bzmoon2 -r
      - mv /tmp/bzmoon2/* /tmp/bzmoon
      - zip -j -r /bzmoon/bzmoon.zip /tmp/bzmoon

      - \cp -f /tmp/bzmoon.zip /mnt/primary/nginx-fs/files/public/bzmoon/bzmoon_${DRONE_TAG}.zip || true
      - \cp -f /tmp/bzmoon.zip /mnt/primary/nginx-fs/files/public/bzmoon/bzmoon_latest.zip || true


  upload:
    image: docker.dock1.spaceway.network/bzone/bztools:latest
    when:
      event:
        - tag
    volumes:
      - /srv/data/caddy/media/public/bzmoon:/builds
    commands:
      - cp -f /tmp/bzmoon.zip /builds/bzmoon_${DRONE_TAG}.zip
      - ln -f /builds/bzmoon_${DRONE_TAG}.zip /builds/bzmoon_latest.zip

