workspace:
  path: /bzmoon

kind: pipeline
name: default

steps:
- name: bundle
  image: thejanne/bztools:latest
  commands:
  when:
    branch:
    - master
    event:
    - tag
  commands:
    - mkdir -p /tmp/bzmoon
    - mkdir -p /tmp/bzmoon2
    - mkdir -p /bzmoon/build
    - moonc /bzmoon/src
    - cp /bzmoon/extra/* /tmp/bzmoon
    - find /bzmoon/src -type f -name "*.lua" -exec cp {} /tmp/bzmoon \;
    - cp /bzmoon/.squish /tmp/bzmoon
    - cp -r /tmp/bzmoon/. /tmp/bzmoon2/
    - python3 /bztools/luaSquish.py /tmp/bzmoon2 -r
    - mv /tmp/bzmoon2/* /tmp/bzmoon
    - rm /tmp/bzmoon/bzpre_1.5.dll
    - rm /tmp/bzmoon/bzpre_bzr.dll
    - cp /bzmoon/extra/bzpre_1.5.dll /tmp/bzmoon/bzpre.dll
    - zip -j -r /bzmoon/build/bzmoon_1.5_${DRONE_TAG}.zip /tmp/bzmoon
    - cp /bzmoon/extra/bzpre_bzr.dll /tmp/bzmoon/bzpre.dll
    - zip -j -r /bzmoon/build/bzmoon_bzr_${DRONE_TAG}.zip /tmp/bzmoon
    - cp /bzmoon/build/bzmoon_bzr_${DRONE_TAG}.zip /bzmoon/build/bzmoon_bzr_latest.zip
    - cp /bzmoon/build/bzmoon_1.5_${DRONE_TAG}.zip /bzmoon/build/bzmoon_1.5_latest.zip

- name: upload
  image: plugins/s3
  settings:
    bucket: buildstorage
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
    source: /bzmoon/build/*.zip
    target: /battlezone/
    acl: public-read
    endpoint: https://s3.nl-ams.scw.cloud
    region: nl-ams

  when:
    event:
      - tag