workspace:
  base: /bzmoon
  path: repo/${DRONE_REPO_SLUG}

pipeline:
  bundler:
    image: docker.faavne.no/bzone/bztools:latest
    when:
      event:
        - tag
    commands:
      - mkdir -p /tmp/bzmoon
      - mkdir -p /tmp/bzmoon2
      - moonc /bzmoon/repo/src
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - curl -O https://raw.githubusercontent.com/bakpakin/tiny-ecs/master/tiny.lua
      - curl -O https://raw.githubusercontent.com/rxi/json.lua/master/json.lua
      - mv rx.lua /tmp/bzmoon
      - mv tiny.lua /tmp/bzmoon
      - mv json.lua /tmp/bzmoon
      - find /bzmoon/repo/src -type f -name "*.lua" -exec cp {} /tmp/bzmoon \;
      - cp /bzmoon/repo/.squish /tmp/bzmoon
      - cp -r /tmp/bzmoon/. /tmp/bzmoon2/
      - python3 /bztools/luaSquish.py /tmp/bzmoon2 -r
      - mv /tmp/bzmoon2/* /tmp/bzmoon
      - cp /bzmoon/repo/extra/* /tmp/bzmoon
      - zip -j -r /bzmoon/bzmoon.zip /tmp/bzmoon

  upload:
    image: appleboy/drone-scp
    host: faavne.no
    username: root
    secrets: [ssh_key]
    key_path: /ssh/id_rsa
    when:
      event:
        - tag
    target:
      - /tmp/
    source:
      - /bzmoon/bzmoon.zip
    strip_components: 1

    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa


  release:
    group: deploy
    image: appleboy/drone-ssh
    host: faavne.no
    username: root
    key_path: /ssh/id_rsa
    secrets: [ssh_key]
    when:
      event:
        - tag
    script:
      - \cp -f /tmp/bzmoon.zip /mnt/primary/nginx-fs/files/public/bzmoon/bzmoon_${DRONE_TAG}.zip || true
      - \cp -f /tmp/bzmoon.zip /mnt/primary/nginx-fs/files/public/bzmoon/bzmoon_latest.zip || true

    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa
