workspace:
  base: /bzmoon
  path: src/${DRONE_REPO_SLUG}

pipeline:
  moon-builder:
    image: abaez/luarocks
    when:
      event:
        - tag
        
    commands:
      - luarocks install moonscript
      - mkdir -p /bzmoon/output
      - moonc /bzmoon/src
      - find /bzmoon/src -name '*.lua' -type f -exec rsync -rv {} /moonc/output \;
  bundler:
    image: localhost:5000/builder
    when:
      event:
        - tag
    commands:
      - zip -j -r /bzmoon/output/bundle.zip /bzmoon/output
      - \cp -f /bzmoon/output/bundle.zip /drone/deploy/bzmoon_${DRONE_TAG}.zip || true
    volumes:
      - /root/studynator/nginx-fs/public/bzmoon/:/drone/deploy

