workspace:
  base: /bzmoon
  path: repo/${DRONE_REPO_SLUG}

pipeline:
  bundler:
    image: docker.studynator.me/bzone/bztools:latest
    when:
      event:
        - tag
    commands:
      - mkdir -p /tmp/bzmoon
      - mkdir -p /tmp/bzmoon2
      - moonc /bzmoon/repo/src
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - mv rx.lua /tmp/bzmoon
      - find /bzmoon/repo/src -type f -name "*.lua" -exec cp {} /tmp/bzmoon \;
      - cp /bzmoon/repo/.squish /tmp/bzmoon
      - cp -r /tmp/bzmoon/. /tmp/bzmoon2/
      - python3 /bztools/luaSquish.py /tmp/bzmoon2 -r
      - mv /tmp/bzmoon2/* /tmp/bzmoon
      - zip -j -r /tmp/bundle.zip /tmp/bzmoon -i '*.lua'
      - \cp -f /tmp/bundle.zip /drone/deploy/bzmoon_${DRONE_TAG}.zip || true
      - \cp -f /tmp/bundle.zip /drone/deploy/bzmoon_latest.zip || true
    volumes:
      - /root/studynator/nginx-fs/public/bzmoon/:/drone/deploy

